name: build-app
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install PyInstaller
        run: |
          pip install pyinstaller
          pyinstaller --version
      - name: Build the app
        run: |
          python -m PyInstaller app.py --noconfirm \
            --add-data static:static \
            --add-data templates:templates \
            --copy-metadata tqdm \
            --copy-metadata regex \
            --copy-metadata requests \
            --copy-metadata packaging \
            --copy-metadata filelock \
            --copy-metadata numpy \
            --copy-metadata tokenizers \
            --copy-metadata huggingface-hub \
            --copy-metadata safetensors \
            --copy-metadata pyyaml \
            --copy-metadata torch
      - name: List output files
        run: find ./dist
