name: build-app
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install PyInstaller
        run: |
          pip install pyinstaller
          pyinstaller --version
      - name: Install Requirements
        run: |
          pip install torch --index-url https://download.pytorch.org/whl/cpu
          pip install -r requirements.txt
          pip freeze
      - name: Build infer.so
        run: |
          cmake -B build_infer
          cmake --build build_infer
          ln -s "$(find build_infer -name infer\*.so)"
      - name: Build the app
        run: |
          python -m PyInstaller app.py --noconfirm \
            --add-data static:static \
            --add-data templates:templates \
            --copy-metadata tqdm \
            --copy-metadata regex \
            --copy-metadata requests \
            --copy-metadata packaging \
            --copy-metadata filelock \
            --copy-metadata numpy \
            --copy-metadata tokenizers \
            --copy-metadata huggingface-hub \
            --copy-metadata safetensors \
            --copy-metadata pyyaml \
            --copy-metadata torch
      - name: List output files
        run: find ./dist
      - name: List licenses
        run: |
          git clone https://github.com/okdshin/license-grep.git
          pip install license-grep
          python3 -m license_grep \
            --py "$(python -c 'import site; print(site.getsitepackages()[0])')" \
            --write-json license-info.json \
            --write-table table.md \
            --write-grouped-markdown grouped.md \
            --dump-unknown-licenses
          cat grouped.md

