name: build-app
run-name: build-app
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
        pip install pyinstaller
        pyinstaller --version
        python -m PyInstaller app.py --noconfirm \
          --add-data static:static \
          --add-data templates:templates \
          --copy-metadata tqdm \
          --copy-metadata regex \
          --copy-metadata requests \
          --copy-metadata packaging \
          --copy-metadata filelock \
          --copy-metadata numpy \
          --copy-metadata tokenizers \
          --copy-metadata huggingface-hub \
          --copy-metadata safetensors \
          --copy-metadata pyyaml \
          --copy-metadata torch
